version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - dmeert
  labels:
    - dependencies
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - dmeert
  labels:
    - dependencies
